name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.7.4
publish_to: none
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  universal_html: ^2.2.4
  video_player: ^2.9.2
  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
